version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      - "8080:8080"
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
  envoy:
    image: envoyproxy/envoy:v1.26-latest
    ports:
      - "9901:9901"
      - "51051:51051"
    command: ["-c", "/etc/envoy/envoy.yaml", "--service-cluster", "front-proxy"]
    volumes:
      - ./envoy/envoy-demo.yaml:/etc/envoy/envoy.yaml
  opa-envoy:
    image: openpolicyagent/opa:latest-envoy
    ports:
      - "9191:9191"
    command:
      - run
      - --server
      - --config-file=/opa.yaml
      - --log-level=debug
      - /policy.rego
    volumes:
      - ./opa/policy.rego:/policy.rego
      - ./opa/opa.yaml:/opa.yaml
  app:
    image: demo-sidecar-app:v0.0.4
    ports:
      - "8090:8090"
    environment:
    - APP_NAME=backend
    - APP_PORT=8090