apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo-front-app
  labels:
    cloud.googleapis.com/location: asia-northeast1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 30
      containers:
        - image: asia-northeast1-docker.pkg.dev/ca-masem-test/any-container/front-app:v0.0.2
          name: front-app
          ports:
            containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
  traffic:
    - percent: 100
      latestRevision: true
