apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo-sidecar-auth-app
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 30
      containers:
        - image: asia-northeast1-docker.pkg.dev/ca-masem-test/any-container/demo-sidecar-app:v0.0.5
          name: backend-app
          env:
            - name: APP_NAME
              value: 'backend'
            - name: APP_PORT
              value: '8090'
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
        - image: asia-northeast1-docker.pkg.dev/ca-masem-test/any-container/envoy:1.26.1-u5
          name: envoy-proxy
          ports:
            containerPort: 51051
          args:
          - "-c"
          - "/etc/envoy/envoy.yaml"
          - "--service-cluster"
          - "front-proxy"
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
        - image: asia-northeast1-docker.pkg.dev/ca-masem-test/any-container/opa:envoy-u2
          name: opa
          args:
          - "run"
          - "--server"
          - "--config-file=/opa.yaml"
          - "--log-level=debug"
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
  traffic:
    - percent: 100
      latestRevision: true
